import Footer from "../../components/footer/Footer";
import Header from "../../components/header/Header";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header id="header-section" />
        {children}
        <section id="contact-section"><Footer /></section>
      </body>
    </html>
  );
}
